<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OmanPrint.Desktop</RootNamespace>
    <ApplicationIcon />
    <StartupObject>OmanPrint.Desktop.App</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OmanPrint.Core\OmanPrint.Core.csproj" />
    <ProjectReference Include="..\OmanPrint.ApiClient\OmanPrint.ApiClient.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>
</Project>
