<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OmanPrint.ApiClient</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OmanPrint.Core\OmanPrint.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SocketIOClient" Version="3.1.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
</Project>
